### PR TITLE
Developer tool : ) Now you're all added :D

### PR DESCRIPTION
**Pull request by OliverDatGuy**
You know those pesky moments when you're like "GRR, I REALLY NEED TO HOP ON LE CONSOLE, BUT I CAN'T BE BOTHERED"? Now all you gotta do is '.command' and BOOM! Whatever you replace "command" with is sent via console! I.E '.say this server is the best' the output would be "[Server] this server is the best".

plz accept ;-;

### CODE REVIEW

**Comment by xDestroyer217** [comment]
Screw it fuckboy approved.

**Comment by OliverDatGuy** [comment]
i lubs you

**Comment by xDestroyer217** [comment]
guess wht tho

**Comment by OliverDatGuy** [comment]
?

**Comment by TheRevalation** [comment]
Forgetting someone dickass?

**Comment by OliverDatGuy** [comment]
no, not at all

**Comment by TheRevalation** [comment]
Fuck u bby

**Comment by tylerhyperHD** [comment]
No fuck me hard.

**Pull request merged**
